# Generated by Django 5.2.9 on 2026-01-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_delete_staff'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='center_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='health_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='centers.healthcenter', verbose_name='المركز الصحي'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير النظام'), ('CENTER_MANAGER', 'مدير مركز'), ('CENTER_STAFF', 'موظف مركز'), ('CUSTOMER', 'ولي أمر')], default='CENTER_STAFF', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
