# Generated by Django 5.2.6 on 2026-02-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='رمز جهاز الإشعارات (FCM Token)'),
        ),
    ]
