# Generated by Django 5.2.6 on 2026-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير النظام'), ('CENTER_MANAGER', 'مدير مركز'), ('CENTER_STAFF', 'موظف مركز'), ('CUSTOMER', 'ولي أمر'), ('MINISTRY', 'مكتب الصحة')], default='CENTER_STAFF', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
