Project "None" {
  database_type: 'PostgreSQL'
  Note: '''None
  Last Updated At 03-29-2026 02:21PM UTC'''
}

enum admin.positive_small_integer_logentry_action_flag {
  "1" [note: '''إضافة''']
  "2" [note: '''تعديل''']
  "3" [note: '''حذف''']
}

enum medical.char_child_gender {
  "M" [note: '''ذكر''']
  "F" [note: '''أنثى''']
}

enum medical.char_vaccineschedule_stage {
  "BASIC" [note: '''أساسي (رضّع)''']
  "SCHOOL" [note: '''مدرسي (سن المدرسة)''']
}

enum notifications.char_notificationlog_notification_type {
  "REMINDER" [note: '''تذكير بموعد''']
  "MISSED" [note: '''تنبيه تأخير''']
  "SYSTEM" [note: '''إشعار نظام''']
}

enum users.char_customuser_role {
  "ADMIN" [note: '''مدير النظام''']
  "CENTER_MANAGER" [note: '''مدير مركز''']
  "CENTER_STAFF" [note: '''موظف مركز''']
  "CUSTOMER" [note: '''ولي أمر''']
  "MINISTRY" [note: '''وزارة الصحة''']
}

Table admin.LogEntry {
  Note: '''
LogEntry(id, action_time, user, content_type, object_id, object_repr, action_flag, change_message)

*DB table: django_admin_log*'''

  id auto [pk, unique, not null]
  action_time date_time [default:`django.utils.timezone.now()`, not null]
  user_id foreign_key [not null]
  content_type_id foreign_key [null]
  object_id text [null]
  object_repr char [not null]
  action_flag admin.positive_small_integer_logentry_action_flag [not null]
  change_message text [not null]

  indexes {
    (content_type_id) [name: 'django_admin_log_content_type_id_c4bce8eb', type: btree]
    (id) [pk, unique, name: 'django_admin_log_pkey', type: btree]
    (user_id) [name: 'django_admin_log_user_id_c564eba6', type: btree]
  }
}
ref: admin.LogEntry.user_id > users.CustomUser.id
ref: admin.LogEntry.content_type_id > contenttypes.ContentType.id


Table auth.Group {
  Note: '''
Groups are a generic way of categorizing users to apply permissions, or
some other label, to those users. A user can belong to any number of
groups.

A user in a group automatically has all the permissions granted to that
group. For example, if the group 'Site editors' has the permission
can_edit_home_page, any user in that group will have that permission.

Beyond permissions, groups are a convenient way to categorize users to
apply some label, or extended functionality, to them. For example, you
could create a group 'Special users', and you could write code that would
do special things to those users -- such as giving them access to a
members-only portion of your site, or sending them members-only email
messages.


*DB table: auth_group*'''

  id auto [pk, unique, not null]
  name char [unique, not null]

  indexes {
    (name) [unique, name: 'auth_group_name_key', type: btree]
    (id) [pk, unique, name: 'auth_group_pkey', type: btree]
  }
}


Table auth.Permission {
  Note: '''
The permissions system provides a way to assign permissions to specific
users and groups of users.

The permission system is used by the Django admin site, but may also be
useful in your own code. The Django admin site uses permissions as follows:

- The "add" permission limits the user's ability to view the "add" form
and add an object.
- The "change" permission limits a user's ability to view the change
list, view the "change" form and change an object.
- The "delete" permission limits the ability to delete an object.
- The "view" permission limits the ability to view an object.

Permissions are set globally per type of object, not per specific object
instance. It is possible to say "Mary may change news stories," but it's
not currently possible to say "Mary may change news stories, but only the
ones she created herself" or "Mary may only change news stories that have a
certain status or publication date."

The permissions listed above are automatically created for each model.


*DB table: auth_permission*'''

  id auto [pk, unique, not null]
  name char [not null]
  content_type_id foreign_key [not null]
  codename char [not null]

  indexes {
    (content_type_id) [name: 'auth_permission_content_type_id_2f476e4b', type: btree]
    (content_type_id,codename) [unique, name: 'auth_permission_content_type_id_codename_01ab375a_uniq', type: btree]
    (id) [pk, unique, name: 'auth_permission_pkey', type: btree]
  }
}
ref: auth.Permission.content_type_id > contenttypes.ContentType.id


Table auth.group_permissions {
  Note: '''
This is a Many-To-Many linking table autogenerated by Django.

*DB table: auth_group_permissions*'''

  id auto [pk, not null]
  permission_id auto
  group_id auto

  indexes {
    (group_id) [name: 'auth_group_permissions_group_id_b120cbf9', type: btree]
    (group_id,permission_id) [unique, name: 'auth_group_permissions_group_id_permission_id_0cd325b0_uniq', type: btree]
    (permission_id) [name: 'auth_group_permissions_permission_id_84c5c92e', type: btree]
    (id) [pk, unique, name: 'auth_group_permissions_pkey', type: btree]
  }
}
ref: auth.Group.id > auth.group_permissions.group_id
ref: auth.Permission.id > auth.group_permissions.permission_id


Table authtoken.Token {
  Note: '''
The default authorization token model.


*DB table: authtoken_token*'''

  key char [pk, unique, not null]
  user_id one_to_one [unique, not null]
  created date_time [not null]

  indexes {
    (key) [pk, unique, name: 'authtoken_token_pkey', type: btree]
    (user_id) [unique, name: 'authtoken_token_user_id_key', type: btree]
  }
}
ref: authtoken.Token.user_id - users.CustomUser.id


Table authtoken.TokenProxy {
  Note: '''
Proxy mapping pk to user pk for use in admin.


*DB table: authtoken_token*'''

  key char [pk, unique, not null]
  user_id one_to_one [unique, not null]
  created date_time [not null]

  indexes {
    (key) [pk, unique, name: 'authtoken_token_pkey', type: btree]
    (user_id) [unique, name: 'authtoken_token_user_id_key', type: btree]
  }
}
ref: authtoken.TokenProxy.user_id - users.CustomUser.id


Table centers.Directorate {
  Note: '''
Directorate(id, governorate, name_ar, name_en, code)

*DB table: centers_directorate*'''

  id big_auto [pk, unique, not null]
  governorate_id foreign_key [not null]
  name_ar char [not null]
  name_en char [null]
  code char [note: '''مثلاً 01 للمشنة''', not null]

  indexes {
    (governorate_id) [name: 'centers_directorate_governorate_id_7179db03', type: btree]
    (governorate_id,code) [unique, name: 'centers_directorate_governorate_id_code_03162eea_uniq', type: btree]
    (id) [pk, unique, name: 'centers_directorate_pkey', type: btree]
  }
}
ref: centers.Directorate.governorate_id > centers.Governorate.id


Table centers.Governorate {
  Note: '''
Governorate(id, name_ar, name_en, code)

*DB table: centers_governorate*'''

  id big_auto [pk, unique, not null]
  name_ar char [not null]
  name_en char [null]
  code char [note: '''مثلاً 14 لإب''', unique, not null]

  indexes {
    (code) [unique, name: 'centers_governorate_code_key', type: btree]
    (id) [pk, unique, name: 'centers_governorate_pkey', type: btree]
  }
}


Table centers.HealthCenter {
  Note: '''
HealthCenter(id, governorate, directorate, center_code, name_ar, name_en, address, working_hours, license_number, is_active, created_at)

*DB table: centers_healthcenter*'''

  id big_auto [pk, unique, not null]
  governorate_id foreign_key [null]
  directorate_id chained_foreign_key [null]
  center_code char [unique, not null]
  name_ar char [not null]
  name_en char [null]
  address text [not null]
  working_hours char [null]
  license_number char [note: '''رقم آخر غير كود المركز''', null]
  is_active boolean [default:`True`, not null]
  created_at date_time [not null]

  indexes {
    (center_code) [unique, name: 'centers_healthcenter_center_code_key', type: btree]
    (directorate_id) [name: 'centers_healthcenter_directorate_id_90e6e4de', type: btree]
    (governorate_id) [name: 'centers_healthcenter_governorate_id_8a42fa22', type: btree]
    (id) [pk, unique, name: 'centers_healthcenter_pkey', type: btree]
  }
}
ref: centers.HealthCenter.governorate_id > centers.Governorate.id
ref: centers.HealthCenter.directorate_id > centers.Directorate.id


Table contenttypes.ContentType {
  Note: '''
ContentType(id, app_label, model)

*DB table: django_content_type*'''

  id auto [pk, unique, not null]
  app_label char [not null]
  model char [not null]

  indexes {
    (app_label,model) [unique, name: 'django_content_type_app_label_model_76bd3d3b_uniq', type: btree]
    (id) [pk, unique, name: 'django_content_type_pkey', type: btree]
  }
}


Table medical.Child {
  Note: '''
Child(id, full_name, gender, date_of_birth, family, health_center, birth_governorate, birth_directorate, place_of_birth, is_completed, completed_date, created_at, created_by)

*DB table: medical_child*'''

  id big_auto [pk, unique, not null]
  full_name char [not null]
  gender medical.char_child_gender [not null]
  date_of_birth date [not null]
  family_id foreign_key [not null]
  health_center_id foreign_key [null]
  birth_governorate_id foreign_key [null]
  birth_directorate_id foreign_key [null]
  place_of_birth char [not null]
  is_completed boolean [default:`False`, not null]
  completed_date date [null]
  created_at date_time [not null]
  created_by_id foreign_key [null]

  indexes {
    (birth_directorate_id) [name: 'medical_child_birth_directorate_id_06786b5d', type: btree]
    (birth_governorate_id) [name: 'medical_child_birth_governorate_id_2eb76419', type: btree]
    (created_by_id) [name: 'medical_child_created_by_id_b923d604', type: btree]
    (family_id) [name: 'medical_child_family_id_d7ede0fe', type: btree]
    (health_center_id) [name: 'medical_child_health_center_id_a6ec1529', type: btree]
    (id) [pk, unique, name: 'medical_child_pkey', type: btree]
  }
}
ref: medical.Child.family_id > medical.Family.id
ref: medical.Child.health_center_id > centers.HealthCenter.id
ref: medical.Child.birth_governorate_id > centers.Governorate.id
ref: medical.Child.birth_directorate_id > centers.Directorate.id
ref: medical.Child.created_by_id > users.CustomUser.id


Table medical.ChildVaccineSchedule {
  Note: '''
الجدول الزمني الخاص بالطفل (يتم إنشاؤه عند تسجيل الطفل).
يحتوي على مواعيد الاستحقاق الخاصة بهذا الطفل بناء على تاريخ ميلاده.


*DB table: medical_childvaccineschedule*'''

  id big_auto [pk, unique, not null]
  child_id foreign_key [not null]
  vaccine_schedule_id foreign_key [not null]
  due_date date [not null]
  is_taken boolean [default:`False`, not null]

  indexes {
    (child_id) [name: 'medical_childvaccineschedule_child_id_1a68e796', type: btree]
    (id) [pk, unique, name: 'medical_childvaccineschedule_pkey', type: btree]
    (vaccine_schedule_id) [name: 'medical_childvaccineschedule_vaccine_schedule_id_136c299a', type: btree]
  }
}
ref: medical.ChildVaccineSchedule.child_id > medical.Child.id
ref: medical.ChildVaccineSchedule.vaccine_schedule_id > medical.VaccineSchedule.id


Table medical.Family {
  Note: '''
جدول العائلة الجديد:
- يحل محل الأب والأم المنفصلين.
- الحساب مرتبط به (User).
- المعرف الفريد هو (اسم الأب + اسم الأم).


*DB table: medical_family*'''

  id big_auto [pk, unique, not null]
  created_at date_time [not null]
  created_by_id foreign_key [null]
  father_name char [not null]
  mother_name char [not null]
  account_id one_to_one [unique, null]
  access_code char [unique, not null]
  notes text [null]

  indexes {
    (access_code) [unique, name: 'medical_family_access_code_key', type: btree]
    (account_id) [unique, name: 'medical_family_account_id_key', type: btree]
    (created_by_id) [name: 'medical_family_created_by_id_e0fd3e5c', type: btree]
    (id) [pk, unique, name: 'medical_family_pkey', type: btree]
  }
}
ref: medical.Family.created_by_id > users.CustomUser.id
ref: medical.Family.account_id - users.CustomUser.id


Table medical.Vaccine {
  Note: '''
Vaccine(id, name_ar, name_en, key, description, is_active)

*DB table: medical_vaccine*'''

  id big_auto [pk, unique, not null]
  name_ar char [not null]
  name_en char [null]
  key char [note: '''المفتاح المستخدم في JS لمطابقة عمود اللقاح. مثال: Pentavalent Vaccine''', null]
  description text [null]
  is_active boolean [default:`True`, not null]

  indexes {
    (id) [pk, unique, name: 'medical_vaccine_pkey', type: btree]
  }
}


Table medical.VaccineRecord {
  Note: '''
VaccineRecord(id, child, vaccine, dose_number, date_given, staff, notes, created_at)

*DB table: medical_vaccinerecord*'''

  id big_auto [pk, unique, not null]
  child_id foreign_key [not null]
  vaccine_id foreign_key [not null]
  dose_number positive_integer [not null]
  date_given date [not null]
  staff_id foreign_key [not null]
  notes text [null]
  created_at date_time [not null]

  indexes {
    (child_id) [name: 'medical_vaccinerecord_child_id_fdbd75e6', type: btree]
    (child_id,vaccine_id,dose_number) [unique, name: 'medical_vaccinerecord_child_id_vaccine_id_dose_c3fcb8bb_uniq', type: btree]
    (id) [pk, unique, name: 'medical_vaccinerecord_pkey', type: btree]
    (staff_id) [name: 'medical_vaccinerecord_staff_id_dbab0966', type: btree]
    (vaccine_id) [name: 'medical_vaccinerecord_vaccine_id_be6cddf6', type: btree]
  }
}
ref: medical.VaccineRecord.child_id > medical.Child.id
ref: medical.VaccineRecord.vaccine_id > medical.Vaccine.id
ref: medical.VaccineRecord.staff_id > users.CustomUser.id


Table medical.VaccineSchedule {
  Note: '''
VaccineSchedule(id, vaccine, dose_number, age_in_months, stage)

*DB table: medical_vaccineschedule*'''

  id big_auto [pk, unique, not null]
  vaccine_id foreign_key [not null]
  dose_number positive_integer [not null]
  age_in_months float [note: '''0 تعني عند الولادة''', not null]
  stage medical.char_vaccineschedule_stage [default:`"BASIC"`, not null]

  indexes {
    (id) [pk, unique, name: 'medical_vaccineschedule_pkey', type: btree]
    (vaccine_id) [name: 'medical_vaccineschedule_vaccine_id_aaabc5d4', type: btree]
  }
}
ref: medical.VaccineSchedule.vaccine_id > medical.Vaccine.id


Table notifications.NotificationLog {
  Note: '''
سجل الإشعارات - Notification History
يستخدم للمحاكاة (Simulation) وللتدقيق (Audit Log)


*DB table: notifications_notificationlog*'''

  id big_auto [pk, unique, not null]
  recipient_id foreign_key [not null]
  title char [not null]
  body text [not null]
  notification_type notifications.char_notificationlog_notification_type [default:`"SYSTEM"`, not null]
  sent_via_fcm boolean [default:`False`, not null]
  fcm_response text [null]
  is_read boolean [default:`False`, not null]
  created_at date_time [not null]

  indexes {
    (id) [pk, unique, name: 'notifications_notificationlog_pkey', type: btree]
    (recipient_id) [name: 'notifications_notificationlog_recipient_id_55bc8f51', type: btree]
  }
}
ref: notifications.NotificationLog.recipient_id > users.CustomUser.id


Table sessions.Session {
  Note: '''
Django provides full support for anonymous sessions. The session
framework lets you store and retrieve arbitrary data on a
per-site-visitor basis. It stores data on the server side and
abstracts the sending and receiving of cookies. Cookies contain a
session ID -- not the data itself.

The Django sessions framework is entirely cookie-based. It does
not fall back to putting session IDs in URLs. This is an intentional
design decision. Not only does that behavior make URLs ugly, it makes
your site vulnerable to session-ID theft via the "Referer" header.

For complete documentation on using Sessions in your code, consult
the sessions documentation that is shipped with Django (also available
on the Django web site).


*DB table: django_session*'''

  session_key char [pk, unique, not null]
  session_data text [not null]
  expire_date date_time [not null]

  indexes {
    (expire_date) [name: 'django_session_expire_date_a5c62663', type: btree]
    (session_key) [pk, unique, name: 'django_session_pkey', type: btree]
  }
}


Table users.CustomUser {
  Note: '''
CustomUser(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, health_center, phone, fcm_token)

*DB table: users_customuser*'''

  id big_auto [pk, unique, not null]
  password char [not null]
  last_login date_time [null]
  is_superuser boolean [note: '''يقضي بأن هذا المستخدم يمتلك كافة الصلاحيات دون الحاجة لمنحها له تصريحاً.''', default:`False`, not null]
  username char [note: '''مطلوب. 150 رمزاً أو أقل، مكونة من حروف وأرقام و @/./+/-/_ فقط''', unique, not null]
  first_name char [not null]
  last_name char [not null]
  email email [not null]
  is_staff boolean [note: '''يحدد ما إذا كان يمكن للمستخدم الدخول إلى موقع الإدارة هذا.''', default:`False`, not null]
  is_active boolean [note: '''يحدد ما إذا كان المستخدم سيُعامل على أنّه نشط. أزل تحديد هذا الحقل بدلاً من حذف الحسابات.''', default:`True`, not null]
  date_joined date_time [default:`django.utils.timezone.now()`, not null]
  role users.char_customuser_role [default:`"CENTER_STAFF"`, not null]
  health_center_id foreign_key [null]
  phone char [null]
  fcm_token text [null]

  indexes {
    (health_center_id) [name: 'users_customuser_health_center_id_9af4bf21', type: btree]
    (id) [pk, unique, name: 'users_customuser_pkey', type: btree]
    (username) [unique, name: 'users_customuser_username_key', type: btree]
  }
}
ref: users.CustomUser.health_center_id > centers.HealthCenter.id


Table users.customuser_groups {
  Note: '''
This is a Many-To-Many linking table autogenerated by Django.

*DB table: users_customuser_groups*'''

  id auto [pk, not null]
  group_id auto
  customuser_id auto

  indexes {
    (customuser_id) [name: 'users_customuser_groups_customuser_id_958147bf', type: btree]
    (customuser_id,group_id) [unique, name: 'users_customuser_groups_customuser_id_group_id_76b619e3_uniq', type: btree]
    (group_id) [name: 'users_customuser_groups_group_id_01390b14', type: btree]
    (id) [pk, unique, name: 'users_customuser_groups_pkey', type: btree]
  }
}
ref: users.CustomUser.id > users.customuser_groups.customuser_id
ref: auth.Group.id > users.customuser_groups.group_id


Table users.customuser_user_permissions {
  Note: '''
This is a Many-To-Many linking table autogenerated by Django.

*DB table: users_customuser_user_permissions*'''

  id auto [pk, not null]
  permission_id auto
  customuser_id auto

  indexes {
    (customuser_id,permission_id) [unique, name: 'users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq', type: btree]
    (customuser_id) [name: 'users_customuser_user_permissions_customuser_id_5771478b', type: btree]
    (permission_id) [name: 'users_customuser_user_permissions_permission_id_baaa2f74', type: btree]
    (id) [pk, unique, name: 'users_customuser_user_permissions_pkey', type: btree]
  }
}
ref: users.CustomUser.id > users.customuser_user_permissions.customuser_id
ref: auth.Permission.id > users.customuser_user_permissions.permission_id


