# Generated by Django 5.2.9 on 2026-01-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0002_remove_healthcenter_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم اللقاح (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم اللقاح (إنجليزي)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف اللقاح')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('father_name', models.CharField(max_length=255, verbose_name='اسم الأب الرباعي')),
                ('mother_name', models.CharField(max_length=255, verbose_name='اسم الأم الرباعي')),
                ('access_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الحساب (ID)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف عائلة',
                'verbose_name_plural': 'ملفات العائلات',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='اسم الطفل (الأول)')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('place_of_birth_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الميلاد (تفصيل)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل التحصين (مؤرشف)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.directorate', verbose_name='مديرية الميلاد')),
                ('birth_governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.governorate', verbose_name='محافظة الميلاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_children', to=settings.AUTH_USER_MODEL)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='centers.healthcenter', verbose_name='مركز التسجيل')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='medical.family', verbose_name='العائلة')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(verbose_name='رقم الجرعة')),
                ('age_in_months', models.PositiveIntegerField(help_text='0 تعني عند الولادة', verbose_name='العمر بالأشهر')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medical.vaccine')),
            ],
            options={
                'ordering': ['age_in_months', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField()),
                ('date_given', models.DateField(verbose_name='تاريخ الإعطاء')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='medical.child')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.vaccine')),
            ],
            options={
                'unique_together': {('child', 'vaccine', 'dose_number')},
            },
        ),
    ]
