# Generated by Django 5.2.9 on 2026-01-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('is_taken', models.BooleanField(default=False, verbose_name='تم أخذ اللقاح')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_schedule', to='medical.child')),
                ('vaccine_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.vaccineschedule')),
            ],
        ),
    ]
