# Generated by Django 5.2.6 on 2026-01-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_childvaccineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطفل (الرباعي)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الطفل (الأول)'),
        ),
    ]
