# Generated by Django 5.2.6 on 2026-01-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_child_full_name_alter_child_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='first_name',
        ),
        migrations.AddField(
            model_name='child',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاكتمال'),
        ),
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.CharField(default='ChildChild', max_length=255, verbose_name='اسم الطفل (الرباعي)'),
            preserve_default=False,
        ),
    ]
