# Generated by Django 5.2.6 on 2026-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_remove_child_first_name_child_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='اسم الطفل (الرباعي)'),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='age_in_months',
            field=models.FloatField(help_text='0 تعني عند الولادة', verbose_name='العمر بالأشهر'),
        ),
    ]
