# Generated by Django 5.2.6 on 2026-02-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_alter_directorate_options_alter_governorate_options_and_more'),
        ('medical', '0005_alter_child_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'طفل', 'verbose_name_plural': 'الأطفال'},
        ),
        migrations.AlterModelOptions(
            name='childvaccineschedule',
            options={'verbose_name': 'استحقاق لقاح', 'verbose_name_plural': 'استحقاقات اللقاحات'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'سجل عائلة', 'verbose_name_plural': 'سجلات العائلات'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'لقاح', 'verbose_name_plural': 'اللقاحات'},
        ),
        migrations.AlterModelOptions(
            name='vaccinerecord',
            options={'verbose_name': 'سجل تطعيم', 'verbose_name_plural': 'سجلات التطعيم'},
        ),
        migrations.AlterModelOptions(
            name='vaccineschedule',
            options={'ordering': ['age_in_months', 'dose_number'], 'verbose_name': 'جدول اللقاحات', 'verbose_name_plural': 'جداول اللقاحات'},
        ),
        migrations.AddField(
            model_name='child',
            name='birth_health_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births', to='centers.healthcenter', verbose_name='مركز الميلاد (المرفق الصحي)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='place_of_birth_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الميلاد (تفصيل/أخرى)'),
        ),
    ]
