# Generated by Django 5.2.6 on 2026-02-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='stage',
            field=models.CharField(choices=[('BASIC', 'أساسي (رضّع)'), ('SCHOOL', 'مدرسي (سن المدرسة)')], default='BASIC', max_length=10, verbose_name='المرحلة'),
        ),
    ]
