# Generated by Django 5.2.6 on 2026-02-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_vaccineschedule_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='birth_health_center',
        ),
        migrations.RemoveField(
            model_name='child',
            name='place_of_birth_detail',
        ),
        migrations.AddField(
            model_name='child',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الميلاد (قرية/منزل/مرفق)'),
        ),
    ]
