# Generated by Django 5.2.6 on 2026-02-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_remove_child_birth_health_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='place_of_birth',
            field=models.CharField(default='غير محدد', max_length=255, verbose_name='مكان الميلاد (قرية/منزل/مرفق)'),
        ),
    ]
