# Generated by Django 5.2.6 on 2026-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_child_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='place_of_birth',
            field=models.CharField(max_length=255, verbose_name='مكان الميلاد (قرية/منزل/مرفق)'),
        ),
    ]
