# Generated by Django 5.2.6 on 2026-02-27 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_alter_directorate_options_alter_governorate_options_and_more'),
        ('medical', '0010_alter_child_place_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'full_name', 'date_of_birth'), name='unique_child_registration'),
        ),
    ]
