# Generated by Django 5.2.6 on 2026-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_child_unique_child_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
    ]
