# Generated by Django 5.2.6 on 2026-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_add_is_active_to_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='key',
            field=models.CharField(blank=True, help_text='المفتاح المستخدم في JS لمطابقة عمود اللقاح. مثال: Pentavalent Vaccine', max_length=100, null=True, verbose_name='مفتاح الواجهة الأمامية (JS Key)'),
        ),
    ]
