# Generated by Django 5.2.6 on 2026-03-31 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_alter_healthcenter_unique_together'),
        ('medical', '0014_populate_vaccine_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='child',
            name='unique_child_registration',
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'full_name'), name='unique_child_registration'),
        ),
    ]
