# Generated by Django 5.2.6 on 2026-04-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_alter_healthcenter_working_hours_centercomplaint'),
        ('medical', '0015_remove_child_unique_child_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerecord',
            name='health_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_records', to='centers.healthcenter', verbose_name='المركز الذي أعطى الجرعة'),
        ),
    ]
