"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-wp1tqnnla2htfvi!epv*m&x!ej3m*$$!^w&6_z4u=n)d^r5vmv')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://care4child-api.onrender.com',
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- 3rd Party Libraries (مكتبات خارجية) ---
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'smart_selects',
    'django_filters',
    'django_extensions',
    'django_dbml',

    # --- My Apps (تطبيقاتنا) ---
    'users.apps.UsersConfig',
    'centers.apps.CentersConfig',
    'medical.apps.MedicalConfig',
    'api',
    'notifications.apps.NotificationsConfig', # إدارة الإشعارات
    'ministry.apps.MinistryConfig',  # وزارة الصحة
    'axes',                          # 🔒 حماية محاولات الاختراق
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Added CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # 🔒 يجب أن يكون آخر واحد
]

ROOT_URLCONF = 'core.urls'
# --- Custom User Model (تفعيل موديل اليوزر الخاص بنا) ---
AUTH_USER_MODEL = 'users.CustomUser'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Main templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ...

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),  # يجب تعريف DATABASE_URL في ملف .env
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Aden'  # اليمن UTC+3

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS — مفتوح في Dev، مقيّد في Production عبر متغير البيئة
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL', 'True') == 'True'
# في production، اضبط CORS_ALLOW_ALL=False في .env وأضف النطاقات المسموح بها:
# CORS_ALLOWED_ORIGINS = ['https://yourapp.com']
CORS_ALLOWED_ORIGINS_REGEXES = []

# Authentication Settings
LOGIN_REDIRECT_URL = 'centers:dashboard'
LOGOUT_REDIRECT_URL = '/users/login/'
LOGIN_URL = '/users/login/'

# REST Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# ======================================================
# 🔒 django-axes — حماية من هجمات Brute Force
# ======================================================
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',          # يجب أن يكون أولاً
    'django.contrib.auth.backends.ModelBackend',
]

from datetime import timedelta

def get_axes_cooloff(request):
    """
    قفل تدريجي - تستقبل الدالة الـ request وليس رقماً:
    - الدورة الأولى  (1-5 فشل)   → دقيقة واحدة
    - الدورة الثانية (6-10 فشل)  → دقيقتان
    - الدورة الثالثة (11-15 فشل) → 4 دقائق
    - وهكذا يتضاعف حتى 60 دقيقة كحد أقصى
    """
    from axes.models import AccessAttempt
    username = ''
    ip_address = ''
    if hasattr(request, 'POST'):
        username = request.POST.get('username', '')
    if hasattr(request, 'META'):
        ip_address = request.META.get('REMOTE_ADDR', '')

    attempt = AccessAttempt.objects.filter(
        username=username,
        ip_address=ip_address,
    ).first()

    failures = attempt.failures_since_start if attempt else 0
    lockout_number = max(1, (failures // 5))       # رقم الدورة الحالية
    minutes = min(2 ** (lockout_number - 1), 60)   # 1, 2, 4, 8 ... حتى 60
    return timedelta(minutes=minutes)

AXES_FAILURE_LIMIT = 5           # عدد المحاولات الخاطئة المسموحة
AXES_COOLOFF_TIME = get_axes_cooloff   # قفل تدريجي (callable)
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # قفل بـ(يوزر + IP) معاً
AXES_RESET_ON_SUCCESS = True     # أعد العداد تلقائياً بعد الدخول الناجح
AXES_VERBOSE = False             # لا نريد سجلات زائدة في الـ console
AXES_LOCKOUT_TEMPLATE = 'axes/lockout.html'  # صفحة القفل المخصصة

def axes_lockout_response(request, credentials, *args, **kwargs):
    """ترسل wait_minutes للصفحة المخصصة حتى يظهر العداد بشكل صحيح."""
    from django.shortcuts import render
    from axes.models import AccessAttempt

    username = credentials.get('username', '')
    ip_address = request.META.get('REMOTE_ADDR', '')

    attempt = AccessAttempt.objects.filter(
        username=username,
        ip_address=ip_address,
    ).first()

    failures = attempt.failures_since_start if attempt else 0
    lockout_number = max(1, failures // 5)
    wait_minutes = min(2 ** (lockout_number - 1), 60)

    return render(request, 'axes/lockout.html', {
        'wait_minutes': wait_minutes,
        'failures': failures,
        'lockout_number': lockout_number,
    }, status=429)

AXES_LOCKOUT_CALLABLE = axes_lockout_response





# Graph Models (django-extensions) — لون رأس الجداول أزرق
GRAPH_MODELS = {
    'color_code_deletions': True,
    'rankdir': 'TB',
    'bgcolor': 'white',
    'fontname': 'Helvetica',
    'node': {
        'shape': 'plaintext',
        'fontname': 'Helvetica',
    },
    'theme': 'original',
    'arrow_shape': 'normal',
    'header_color': '#1D74C4',  # أزرق
}
