# Generated by Django 5.2.6 on 2026-02-19 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('body', models.TextField(verbose_name='نص الإشعار')),
                ('notification_type', models.CharField(choices=[('REMINDER', 'تذكير بموعد'), ('MISSED', 'تنبيه تأخير'), ('SYSTEM', 'إشعار نظام')], default='SYSTEM', max_length=20, verbose_name='نوع الإشعار')),
                ('sent_via_fcm', models.BooleanField(default=False, verbose_name='تم الإرسال عبر FCM؟')),
                ('fcm_response', models.TextField(blank=True, null=True, verbose_name='رد سيرفر FCM')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجل الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
