# Generated by Django 5.2.6 on 2026-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REMINDER', 'تذكير بموعد'), ('MISSED', 'تنبيه تأخير'), ('SYSTEM', 'إشعار نظام'), ('COMPLAINT_PROMPT', 'طلب إبلاغ عن مشكلة')], default='SYSTEM', max_length=20, verbose_name='نوع الإشعار'),
        ),
    ]
