# Generated by Django 5.2.9 on 2026-01-07 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم المحافظة (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المحافظة (إنجليزي)')),
                ('code', models.CharField(help_text='مثلاً 14 لإب', max_length=5, unique=True, verbose_name='كود المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم المديرية (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المديرية (إنجليزي)')),
                ('code', models.CharField(help_text='مثلاً 01 للمشنة', max_length=5, verbose_name='كود المديرية')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='centers.governorate', verbose_name='المحافظة')),
            ],
            options={
                'unique_together': {('governorate', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='كود المركز')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المركز (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المركز (إنجليزي)')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة/المنطقة')),
                ('address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('license_number', models.CharField(blank=True, help_text='رقم آخر غير كود المركز', max_length=50, null=True, verbose_name='رقم الترخيص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centers.directorate', verbose_name='المديرية')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centers.governorate', verbose_name='المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوظيفي')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='centers.healthcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
