# Generated by Django 5.2.9 on 2026-01-08 14:36

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_remove_healthcenter_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='city',
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='directorate',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='governorate', chained_model_field='governorate', null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.directorate', verbose_name='المديرية'),
        ),
    ]
