# Generated by Django 5.2.9 on 2026-01-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_remove_healthcenter_city_healthcenter_working_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
