# Generated by Django 5.2.6 on 2026-02-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_delete_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorate',
            options={'verbose_name': 'مديرية', 'verbose_name_plural': 'المديريات'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'محافظة', 'verbose_name_plural': 'المحافظات'},
        ),
        migrations.AlterModelOptions(
            name='healthcenter',
            options={'verbose_name': 'مركز صحي', 'verbose_name_plural': 'المراكز الصحية'},
        ),
    ]
