# Generated by Django 5.2.6 on 2026-03-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_alter_directorate_options_alter_governorate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='healthcenter',
            unique_together={('name_ar', 'governorate', 'directorate')},
        ),
    ]
