# Generated by Django 5.2.6 on 2026-04-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_alter_healthcenter_unique_together'),
        ('medical', '0015_remove_child_unique_child_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='working_hours',
            field=models.CharField(blank=True, choices=[('فترة صباحية (8:00 ص - 1:00 م)', 'فترة صباحية (8:00 ص - 1:00 م)'), ('فترة مسائية (4:00 م - 9:00 م)', 'فترة مسائية (4:00 م - 9:00 م)'), ('فترتين (8 ص - 1 م / 4 م - 9 م)', 'فترتين (8 ص - 1 م / 4 م - 9 م)'), ('على مدار الساعة (24/7)', 'على مدار الساعة (24/7)')], max_length=255, null=True, verbose_name='ساعات العمل'),
        ),
        migrations.CreateModel(
            name='CenterComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('VACCINE_UNAVAILABLE', 'اللقاح غير متوفر بالمركز'), ('SUBSTITUTE_GIVEN', 'تم إعطاء لقاح بديل'), ('ILLEGAL_FEES', 'طُلبت رسوم مالية غير قانونية'), ('BAD_TREATMENT', 'سوء المعاملة'), ('STAFF_ABSENT', 'غياب الموظفين'), ('OTHER', 'أخرى')], max_length=25, verbose_name='نوع الشكوى')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('REVIEWED', 'تمت المراجعة'), ('RESOLVED', 'تم الحل')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='medical.family', verbose_name='العائلة')),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='centers.healthcenter', verbose_name='المركز المُبلَّغ عنه')),
                ('vaccine_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='medical.vaccinerecord', verbose_name='سجل التطعيم')),
            ],
            options={
                'verbose_name': 'شكوى على مركز',
                'verbose_name_plural': 'شكاوى المراكز',
            },
        ),
    ]
