# Generated by Django 5.2.6 on 2026-04-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_alter_healthcenter_working_hours_centercomplaint'),
        ('medical', '0016_vaccinerecord_health_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercomplaint',
            name='vaccine_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='medical.vaccinerecord', verbose_name='سجل التطعيم'),
        ),
    ]
