# Generated by Django 5.2.6 on 2026-04-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_alter_centercomplaint_vaccine_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('EXCELLENT', 'ممتاز - خدمة رائعة'), ('GOOD', 'جيد - لا توجد ملاحظات'), ('VACCINE_UNAVAILABLE', 'اللقاح غير متوفر بالمركز'), ('SUBSTITUTE_GIVEN', 'تم إعطاء لقاح بديل'), ('ILLEGAL_FEES', 'طُلبت رسوم مالية غير قانونية'), ('BAD_TREATMENT', 'سوء المعاملة'), ('STAFF_ABSENT', 'غياب الموظفين'), ('OTHER', 'أخرى')], max_length=25, verbose_name='نوع الشكوى'),
        ),
    ]
