# Generated by Django 5.2.6 on 2026-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_alter_centercomplaint_complaint_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centercomplaint',
            options={'verbose_name': 'تقييم مركز', 'verbose_name_plural': 'تقييمات المراكز'},
        ),
        migrations.AddField(
            model_name='centercomplaint',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1 نجمة'), (2, '2 نجمة'), (3, '3 نجمة'), (4, '4 نجمة'), (5, '5 نجمة')], null=True, verbose_name='التقييم بالنجوم'),
        ),
        migrations.AlterField(
            model_name='centercomplaint',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'ممتاز - خدمة رائعة'), ('GOOD', 'جيد - لا توجد ملاحظات'), ('VACCINE_UNAVAILABLE', 'اللقاح غير متوفر بالمركز'), ('SUBSTITUTE_GIVEN', 'تم إعطاء لقاح بديل'), ('ILLEGAL_FEES', 'طُلبت رسوم مالية غير قانونية'), ('BAD_TREATMENT', 'سوء المعاملة'), ('STAFF_ABSENT', 'غياب الموظفين'), ('OTHER', 'أخرى')], max_length=25, null=True, verbose_name='نوع الشكوى'),
        ),
        migrations.AlterField(
            model_name='centercomplaint',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق / تفاصيل إضافية'),
        ),
    ]
